export const project_styles = {
    container: {
        minHeight: "100vh",
        background: "linear-gradient(to bottom, #f9fafb, #dbeafe)",
        padding: "2rem 1rem",
    },
    header: {
        maxWidth: "56rem",
        margin: "0 auto 2rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerButton: {
        color: "#4b5563",
        background: "none",
        border: "none",
        cursor: "pointer",
        padding: "0.5rem",
    },
    headerTitle: {
        fontSize: "1.25rem",
        fontWeight: 600,
        color: "#111827",
        margin: 0,
    },
    mainContainer: {
        maxWidth: "56rem",
        margin: "0 auto",
    },
    card: {
        backgroundColor: "white",
        borderRadius: "0.5rem",
        boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        padding: "2rem",
        marginBottom: "1.5rem",
    },
    logoContainer: {
        display: "flex",
        justifyContent: "center",
        marginBottom: "1.5rem",
    },
    brandName: {
        fontSize: "1.875rem",
        fontWeight: 700,
        color: "#1e3a8a",
        textAlign: "center",
        marginBottom: "0.5rem",
    },
    infoSection: {
        marginTop: "2rem",
        display: "flex",
        flexDirection: "column",
        gap: "1rem",
    },
    infoItem: {
        display: "flex",
        alignItems: "flex-start",
        gap: "0.75rem",
        padding: "1rem",
        backgroundColor: "#f9fafb",
        borderRadius: "0.5rem",
    },
    infoIcon: {
        color: "#1e3a8a",
        marginTop: "0.25rem",
        flexShrink: 0,
    },
    infoLabel: {
        fontSize: "0.875rem",
        color: "#4b5563",
        fontWeight: 500,
        marginBottom: "0.25rem",
    },
    infoValue: {
        fontSize: "1.125rem",
        color: "#111827",
    },
    stackContainer: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
    },
    stackBadge: {
        padding: "0.25rem 0.75rem",
        backgroundColor: "#1e3a8a",
        color: "white",
        fontSize: "0.875rem",
        borderRadius: "9999px",
    },
    projectsHeader: {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        marginBottom: "1.5rem",
    },
    projectsTitle: {
        fontSize: "1.5rem",
        fontWeight: 700,
        color: "#1e3a8a",
        margin: 0,
    },
    projectsList: {
        display: "flex",
        flexDirection: "column",
        gap: "1rem",
    },
    projectCard: {
        border: "1px solid #e5e7eb",
        borderRadius: "0.5rem",
        padding: "1.25rem",
        transition: "box-shadow 0.2s",
        cursor: "pointer",
    },
    projectHeader: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        marginBottom: "0.5rem",
    },
    projectName: {
        fontSize: "1.25rem",
        fontWeight: 600,
        color: "#111827",
        margin: 0,
    },
    statusBadge: {
        padding: "0.25rem 0.75rem",
        fontSize: "0.75rem",
        fontWeight: 500,
        borderRadius: "9999px",
    },
    statusCompleted: {
        backgroundColor: "#dcfce7",
        color: "#166534",
    },
    statusInProgress: {
        backgroundColor: "#fef3c7",
        color: "#854d0e",
    },
    projectDescription: {
        color: "#4b5563",
        marginBottom: "0.75rem",
    },
    techList: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
    },
    techBadge: {
        padding: "0.25rem 0.5rem",
        backgroundColor: "#f3f4f6",
        color: "#374151",
        fontSize: "0.75rem",
        borderRadius: "0.25rem",
    },
    loadingContainer: {
        minHeight: "100vh",
        background: "linear-gradient(to bottom, #f9fafb, #dbeafe)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    spinner: {
        display: "inline-block",
        width: "3rem",
        height: "3rem",
        border: "4px solid #e5e7eb",
        borderTopColor: "#1e3a8a",
        borderRadius: "50%",
        animation: "spin 1s linear infinite",
    },
    loadingText: {
        marginTop: "1rem",
        color: "#4b5563",
    },
    errorText: {
        color: "#dc2626",
    },
};